### ISSUE TITLE
Need file requirements for build.bat

### ISSUE THREAD

**Issue by Fabiologik** [ZurinoZ/ZurinoZ-Token-Stealer#2]
Lot of errors i cant use your tool [![image](https://github.com/ZurinoZ/ZurinoZ-Token-Stealer/assets/96794195/e9567c12-e09b-4ed6-a542-ef5415fdd42c)]()

**Comment by ZurinoZ** [comment]
i will fix them

**Comment by ZurinoZ** [comment]
i have now uploaded requirements.txt

**Comment by ZurinoZ** [comment]
let me know if there are any other issues with it

**Comment by Fabiologik** [comment]
Thank you for upload requirements I have other problem with uwu. I has upload pylance but the problem come not here. Do you have another contact? 
![IMG_9319](https://github.com/ZurinoZ/ZurinoZ-Token-Stealer/assets/96794195/496d9205-3d10-4e27-959e-abcf10a39c37)

**Comment by ZurinoZ** [comment]
> Thank you for upload requirements I have other problem with uwu. I has upload pylance but the problem come not here. Do you have another contact? ![IMG_9319](https://private-user-images.githubusercontent.com/96794195/292617513-496d9205-3d10-4e27-959e-abcf10a39c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjk3NzIsIm5iZiI6MTcwMzMyOTQ3MiwicGF0aCI6Ii85Njc5NDE5NS8yOTI2MTc1MTMtNDk2ZDkyMDUtM2QxMC00ZTI3LTk1OWUtYWJjZjEwYTM5YzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDExMDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzMwZGJkOTJlY2FhNzE0Nzg1YmVmY2I3NmRjMWIwMWY5NmYwNmRlYWIzY2ZhOGRiZWUxNzNhNzA0MDA0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PLZVKnLta4L9u8vjm0FQBGifgBy-kFLtly48NGDVShQ)

you can contact me thru telegram @jessebands1 i will fix this later today when i have time
